version: "3.7"
services:
  java-goof:
    user: "laboratorio"
    build:
      context: .
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ~/.m2:/var/maven/.m2 
      - ..:/app
    command: sleep infinity
    network_mode: "host" 
    depends_on: 
      - sonar

  sonar:
    image: sonarqube:latest
    ports:
      - 9000:9000
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - sonar_data:/opt/sonarqube/data
    network_mode: "host" 

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
    network_mode: "host" 


  owasp-zap:
    user: zap
    image: owasp/zap2docker-stable
    # command: zap.sh -daemon -port 8090 -host 0.0.0.0
    command: zap-webswing.sh
    ports:
      - 8090:8090
      - 8080:8080
    network_mode: "host" 


volumes:
  sonar_data:
    driver: local